version: 2
jobs:
  sync:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout

      - run:
        command: yarn sync

workflows:
  version: 2
  build:
    jobs:
      - sync:
        filters:
          branches:
            only: master
